from __future__ import annotations

import time

from arbiter.confidence.quote_verifier import QuoteSource, locate_quote_page, resolve_quote_source, resolve_quote, verify_quote
from arbiter.models import PageBox


def box(page: int, text: str) -> PageBox:
    return PageBox(boxclass="text", text=text, bbox=(0.0, 0.0, 100.0, 100.0), page=page)


def test_verify_quote_exact_match() -> None:
    assert verify_quote("Allocation was centrally concealed.", "Allocation was centrally concealed.")


def test_verify_quote_ignores_case_and_whitespace() -> None:
    stream = "Allocation\n\nwas\tCENTRALLY concealed."

    assert verify_quote("allocation was centrally concealed", stream)


def test_verify_quote_tolerates_common_ocr_artifacts() -> None:
    stream = "The trial used stratiﬁed random-\nization with central allocation."

    assert verify_quote("The trial used stratified randomization with central allocation.", stream)


def test_verify_quote_false_when_absent() -> None:
    stream = "Participants were followed for overall survival."

    assert not verify_quote("The allocation sequence was concealed.", stream)


def test_verify_quote_short_or_empty_quotes_are_unverified(monkeypatch) -> None:
    monkeypatch.setenv("ARBITER_QUOTE_MIN_VERIFY_CHARS", "15")

    assert not verify_quote("", "")
    assert not verify_quote("short quote", "")


def test_verify_quote_accepts_short_exact_match(monkeypatch) -> None:
    monkeypatch.setenv("ARBITER_QUOTE_MIN_VERIFY_CHARS", "15")

    assert verify_quote("Masking: NONE", "[ClinicalTrials.gov]\nMasking: NONE")
    assert not verify_quote("Masking: NONE", "[ClinicalTrials.gov]\nMasking: SINGLE")


def test_verify_quote_completes_under_500ms_for_50000_char_stream() -> None:
    stream = ("A" * 25_000) + " Allocation was centrally concealed. " + ("B" * 25_000)
    start = time.perf_counter()

    assert verify_quote("Allocation was centrally concealed.", stream)

    assert time.perf_counter() - start < 0.5


def test_locate_quote_page_returns_correct_zero_based_page(monkeypatch) -> None:
    monkeypatch.setenv("ARBITER_QUOTE_MIN_VERIFY_CHARS", "15")
    pages = [
        box(0, "Background and trial setting."),
        box(1, "The random allocation sequence was generated by computer."),
        box(2, "Participants were followed until progression."),
    ]

    assert locate_quote_page("random allocation sequence was generated by computer", pages) == 1


def test_locate_quote_page_returns_earlier_page_for_page_break_straddle(monkeypatch) -> None:
    monkeypatch.setenv("ARBITER_QUOTE_MIN_VERIFY_CHARS", "15")
    pages = [
        box(3, "The sequence was generated centrally and allocation was"),
        box(4, "concealed until participants were enrolled and assigned."),
    ]

    assert locate_quote_page("allocation was concealed until participants were enrolled", pages) == 3


def test_locate_quote_page_resolves_quote_spanning_two_boxes_on_one_page(monkeypatch) -> None:
    # A quote split across two boxes on the SAME page verifies against the raw
    # stream but no single box clears the threshold; per-page concatenation must
    # still localise it (regression for the per-box matching gap).
    monkeypatch.setenv("ARBITER_QUOTE_MIN_VERIFY_CHARS", "15")
    pages = [
        box(0, "Background and trial setting."),
        box(2, "The random allocation sequence was"),
        box(2, "concealed until enrolment and assignment."),
    ]

    assert locate_quote_page("allocation sequence was concealed until enrolment", pages) == 2


def test_locate_quote_page_returns_none_for_empty_quote(monkeypatch) -> None:
    monkeypatch.setenv("ARBITER_QUOTE_MIN_VERIFY_CHARS", "15")

    assert locate_quote_page("", [box(0, "Some text")]) is None


def test_locate_quote_page_accepts_short_exact_match(monkeypatch) -> None:
    monkeypatch.setenv("ARBITER_QUOTE_MIN_VERIFY_CHARS", "15")

    assert locate_quote_page("short quote", [box(0, "short quote")]) == 0


def test_locate_quote_page_returns_none_when_absent(monkeypatch) -> None:
    monkeypatch.setenv("ARBITER_QUOTE_MIN_VERIFY_CHARS", "15")

    assert locate_quote_page("Allocation was concealed.", [box(0, "No matching methods text.")]) is None


def test_resolve_quote_never_pages_unverified_quote() -> None:
    verified, page = resolve_quote(
        "Allocation was concealed.",
        "No matching methods text.",
        [box(0, "Allocation was concealed.")],
    )

    assert verified is False
    assert page is None


def test_resolve_quote_treats_absent_short_quote_as_unverified(monkeypatch) -> None:
    monkeypatch.setenv("ARBITER_QUOTE_MIN_VERIFY_CHARS", "15")

    verified, page = resolve_quote("short quote", "no matching text", [box(0, "no matching text")])

    assert verified is False
    assert page is None


def test_resolve_quote_source_verifies_unpaged_registry_short_quote(monkeypatch) -> None:
    monkeypatch.setenv("ARBITER_QUOTE_MIN_VERIFY_CHARS", "15")

    verified, page, source_document = resolve_quote_source(
        "Masking: NONE",
        [
            QuoteSource(
                source_document="ClinicalTrials.gov",
                raw_char_stream="[ClinicalTrials.gov]\nMasking: NONE",
                page_boxes=[],
                page_required=False,
            )
        ],
    )

    assert verified is True
    assert page is None
    assert source_document == "ClinicalTrials.gov"


def test_resolve_quote_requires_page_boxes_for_verified_result() -> None:
    verified, page = resolve_quote(
        "Allocation was centrally concealed until assignment.",
        "Allocation was centrally concealed until assignment.",
        [],
    )

    assert verified is False
    assert page is None


def test_resolve_quote_falls_back_to_best_page_for_verified_quote(monkeypatch) -> None:
    monkeypatch.setenv("ARBITER_QUOTE_MIN_VERIFY_CHARS", "15")

    verified, page = resolve_quote(
        "Allocation was centrally concealed until assignment.",
        "Allocation was centrally concealed until assignment.",
        [
            box(0, "Background text."),
            box(1, "Allocation was concealed until assignment."),
        ],
    )

    assert verified is True
    assert page == 1
